[package]
name = "db_main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db_core = { path = "../db_core" }
tokio = { version = "1.27.0", features = ["full"] }
bincode = "1.3.3"